# Generated by Django 4.2.3 on 2023-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='connection',
            field=models.BooleanField(default=True, help_text='Отметьте, если возможна связь с продавцом', verbose_name='Связь'),
        ),
    ]
