# Generated by Django 4.2.3 on 2023-07-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0002_advertisement_connection'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
